### ISSUE TITLE
open terminal failed: missing or unsuitable terminal: xterm-256color

### ISSUE THREAD

**Issue by yutkat** [nelsonenzo/tmux-appimage#3]
I'm trying tmux appimage version. But it causes an error `open terminal failed: missing or unsuitable terminal: xterm-256color`.

If I set TERM=xterm, it works fine. And non-appimage tmux works with xterm or xterm-256-color.

What is wrong?

### My configuration

* tmux version (`tmux -V`) : tmux 3.0a (AppImageVersion)
* Platform (`uname -sp`) : Linux unknown (ArchLinux)
* $TERM inside and outside of tmux (`echo $TERM`): xterm-256color
* Logs from tmux (`tmux kill-server; tmux -vv new`): open terminal failed: missing or unsuitable terminal: xterm-256color

**Comment by TheMeaningfulEngineer** [comment]
Am having the same issue.
Have built tmux `3.0a` and the problems isn't there when it's run natively on the host but is for the app image.

**Comment by nelsonenzo** [comment]
thanks for the report, I'll take a look.

**Comment by nelsonenzo** [comment]
i was able to reproduce this easily on Manjaro Arch.  No solution yet, but still working on it. 

In an attempt to narrow down the issue, I symlinked 
`ln -fs /usr/share/terminfo/x/xterm-color /usr/share/terminfo/x/xterm-color256`, and was able to use the tmux with TERM=xterm-color256.  While not a solution, it rules out "missing" - it's looking in the right place, but finding xterm-256color "unsuitable".

I suspect the issue lies somewhere with the version of ncurses between centos 6, where this appimage is built, and arch.  I'll need to investigate more.

**Comment by yutkat** [comment]
I see.

So, I found a workaround.
`TERM=xterm tmux -2`

This is no problem for now.

**Comment by matu3ba** [comment]
On other shells like alacritty it fails as well and the workaround does not work there.

**Comment by yutkat** [comment]
I'm using this new appimage tmux.
https://github.com/tmux/tmux/releases/download/3.0a/tmux-3.0a-x86_64.AppImage
https://github.com/nelsonenzo/tmux-appimage/pull/5

It is working fine without workaround. I think this problem is solved.

**Comment by nelsonenzo** [comment]
@matu3ba can you paste the command your running?  And the OS, etc.  I just tested on arch linux in an Alacritty terminal emulator and `TERM=xterm ./tmux-3.0a-x86_64.AppImage -2 ` worked for me.

**Comment by matu3ba** [comment]
Sorry, I forgot to mention that I am not using standard bash, but ion shell. The workaround works.

**Comment by matu3ba** [comment]
The workaround has weird side effects.
For example running `git branch -a` results in `Error: too many environment variables`.

**Comment by michaellee8** [comment]
@nelsonenzo That issue should be because of that very old CentOS only provides libncurse5 which is too old to support 256 color. I have just got vifm working in older OS (I uses Ubuntu 16.04 LTS which only provide libnurses5) by manually compiling libncurses6 and put it into AppImage. I will soon port that effort to tmux as well.

**Comment by michaellee8** [comment]
Please look at my scripr here https://github.com/tmux/tmux/pull/2465

**Comment by pmzgit** [comment]
> 
my pc os env:

deepin20.3 
debian10 
5.10.60-amd64-desktop #3 SMP Tue Nov 9 20:52:29 CST 2021 x86_64 GNU/Linux

`TERM=xterm ./tmux-3.1b-x86_64.AppImage -2` work fine for me
