### ISSUE TITLE
Include man page in AppImage packaging

### ISSUE THREAD

**Issue by jrwrigh** [nelsonenzo/tmux-appimage#6]
It would be nice to have the man page come with the AppImage bundle of tmux such that when doing a `--appimage-extract`, it would be in the `squashfs/share/man` directory. 

Also, thank you so much for making this. I don't have admin privileges on 90% of the machines I work on, so having an AppImage is a God send.

**Comment by nelsonenzo** [comment]
Thank you for the feedback, it's very encouraging to me.  I will look into adding the man page.

**Comment by nelsonenzo** [comment]
Just to get clarity here, are you simply looking for a file like, `squashfs/share/man/tmux.txt`.   I'm not sure how anyone would know it's there. Are there examples where this is a thing you could point me to?  Just want to make sure i get it right because I couldn't find any official appimage standard for including man pages.

**Comment by jrwrigh** [comment]
> Are there examples where this is a thing you could point me to?

neovim puts their man page in `./usr/man/man1` using [this script](https://github.com/neovim/neovim/blob/master/scripts/genappimage.sh).

> I'm not sure how anyone would know it's there.

I'm fair. I don't think that'll change either. TBH, I didn't know nvim packaged there until I looked. I also don't think the man page is accessible without extracting out the appimage (which I don't mind doing personally).

**Comment by nelsonenzo** [comment]
I appreciate your feedback, but I've decided not to add this particular feature.
- The tmux man page is readily available using google. 
- Since it's not a standard appimage feature, it would only be an easter egg for those that looked.

Please let me know if you really feel strongly that this should be added.  Thank you!!!
