### ISSUE TITLE
Do you plan to release a new version?

### ISSUE THREAD

**Issue by yutkat** [nelsonenzo/tmux-appimage#8]
I can't wait for the latest tmux.

**Comment by nelsonenzo** [comment]
I've added releases for 3.1a and 3.1b.   Since I can't get a webhook directly from the tmux repo, the appimage releases will always lag.  You can always build it yourself if you have docker running somewhere with the instructions in the readme to get the very latest.  Thanks!
https://github.com/nelsonenzo/tmux-appimage/releases
